package com.funshion.gamma.media.thrift;
/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum FieldGroupType implements org.apache.thrift.TEnum {
  base(0),
  name(1),
  nameTime(2),
  baseLong(3),
  all(4);

  private final int value;

  private FieldGroupType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static FieldGroupType findByValue(int value) { 
    switch (value) {
      case 0:
        return base;
      case 1:
        return name;
      case 2:
        return nameTime;
      case 3:
        return baseLong;
      case 4:
        return all;
      default:
        return null;
    }
  }
}
