package com.funshion.gamma.media.thrift;
/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class MediaWithClient implements org.apache.thrift.TBase<MediaWithClient, MediaWithClient._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("MediaWithClient");

  private static final org.apache.thrift.protocol.TField MEDIA_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("mediaId", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField CLIENT_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("clientType", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField MEDIA_LAST_NUM_FIELD_DESC = new org.apache.thrift.protocol.TField("mediaLastNum", org.apache.thrift.protocol.TType.I32, (short)3);
  private static final org.apache.thrift.protocol.TField MEDIA_LAST_READABLE_NUM_FIELD_DESC = new org.apache.thrift.protocol.TField("mediaLastReadableNum", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField MEDIA_LAST_UPDATE_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("mediaLastUpdateTime", org.apache.thrift.protocol.TType.STRING, (short)5);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new MediaWithClientStandardSchemeFactory());
    schemes.put(TupleScheme.class, new MediaWithClientTupleSchemeFactory());
  }

  public int mediaId; // required
  public String clientType; // required
  public int mediaLastNum; // required
  public String mediaLastReadableNum; // required
  public String mediaLastUpdateTime; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    MEDIA_ID((short)1, "mediaId"),
    CLIENT_TYPE((short)2, "clientType"),
    MEDIA_LAST_NUM((short)3, "mediaLastNum"),
    MEDIA_LAST_READABLE_NUM((short)4, "mediaLastReadableNum"),
    MEDIA_LAST_UPDATE_TIME((short)5, "mediaLastUpdateTime");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // MEDIA_ID
          return MEDIA_ID;
        case 2: // CLIENT_TYPE
          return CLIENT_TYPE;
        case 3: // MEDIA_LAST_NUM
          return MEDIA_LAST_NUM;
        case 4: // MEDIA_LAST_READABLE_NUM
          return MEDIA_LAST_READABLE_NUM;
        case 5: // MEDIA_LAST_UPDATE_TIME
          return MEDIA_LAST_UPDATE_TIME;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __MEDIAID_ISSET_ID = 0;
  private static final int __MEDIALASTNUM_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.MEDIA_ID, new org.apache.thrift.meta_data.FieldMetaData("mediaId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.CLIENT_TYPE, new org.apache.thrift.meta_data.FieldMetaData("clientType", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.MEDIA_LAST_NUM, new org.apache.thrift.meta_data.FieldMetaData("mediaLastNum", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.MEDIA_LAST_READABLE_NUM, new org.apache.thrift.meta_data.FieldMetaData("mediaLastReadableNum", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.MEDIA_LAST_UPDATE_TIME, new org.apache.thrift.meta_data.FieldMetaData("mediaLastUpdateTime", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(MediaWithClient.class, metaDataMap);
  }

  public MediaWithClient() {
  }

  public MediaWithClient(
    int mediaId,
    String clientType,
    int mediaLastNum,
    String mediaLastReadableNum,
    String mediaLastUpdateTime)
  {
    this();
    this.mediaId = mediaId;
    setMediaIdIsSet(true);
    this.clientType = clientType;
    this.mediaLastNum = mediaLastNum;
    setMediaLastNumIsSet(true);
    this.mediaLastReadableNum = mediaLastReadableNum;
    this.mediaLastUpdateTime = mediaLastUpdateTime;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public MediaWithClient(MediaWithClient other) {
    __isset_bitfield = other.__isset_bitfield;
    this.mediaId = other.mediaId;
    if (other.isSetClientType()) {
      this.clientType = other.clientType;
    }
    this.mediaLastNum = other.mediaLastNum;
    if (other.isSetMediaLastReadableNum()) {
      this.mediaLastReadableNum = other.mediaLastReadableNum;
    }
    if (other.isSetMediaLastUpdateTime()) {
      this.mediaLastUpdateTime = other.mediaLastUpdateTime;
    }
  }

  public MediaWithClient deepCopy() {
    return new MediaWithClient(this);
  }

  @Override
  public void clear() {
    setMediaIdIsSet(false);
    this.mediaId = 0;
    this.clientType = null;
    setMediaLastNumIsSet(false);
    this.mediaLastNum = 0;
    this.mediaLastReadableNum = null;
    this.mediaLastUpdateTime = null;
  }

  public int getMediaId() {
    return this.mediaId;
  }

  public MediaWithClient setMediaId(int mediaId) {
    this.mediaId = mediaId;
    setMediaIdIsSet(true);
    return this;
  }

  public void unsetMediaId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __MEDIAID_ISSET_ID);
  }

  /** Returns true if field mediaId is set (has been assigned a value) and false otherwise */
  public boolean isSetMediaId() {
    return EncodingUtils.testBit(__isset_bitfield, __MEDIAID_ISSET_ID);
  }

  public void setMediaIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __MEDIAID_ISSET_ID, value);
  }

  public String getClientType() {
    return this.clientType;
  }

  public MediaWithClient setClientType(String clientType) {
    this.clientType = clientType;
    return this;
  }

  public void unsetClientType() {
    this.clientType = null;
  }

  /** Returns true if field clientType is set (has been assigned a value) and false otherwise */
  public boolean isSetClientType() {
    return this.clientType != null;
  }

  public void setClientTypeIsSet(boolean value) {
    if (!value) {
      this.clientType = null;
    }
  }

  public int getMediaLastNum() {
    return this.mediaLastNum;
  }

  public MediaWithClient setMediaLastNum(int mediaLastNum) {
    this.mediaLastNum = mediaLastNum;
    setMediaLastNumIsSet(true);
    return this;
  }

  public void unsetMediaLastNum() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __MEDIALASTNUM_ISSET_ID);
  }

  /** Returns true if field mediaLastNum is set (has been assigned a value) and false otherwise */
  public boolean isSetMediaLastNum() {
    return EncodingUtils.testBit(__isset_bitfield, __MEDIALASTNUM_ISSET_ID);
  }

  public void setMediaLastNumIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __MEDIALASTNUM_ISSET_ID, value);
  }

  public String getMediaLastReadableNum() {
    return this.mediaLastReadableNum;
  }

  public MediaWithClient setMediaLastReadableNum(String mediaLastReadableNum) {
    this.mediaLastReadableNum = mediaLastReadableNum;
    return this;
  }

  public void unsetMediaLastReadableNum() {
    this.mediaLastReadableNum = null;
  }

  /** Returns true if field mediaLastReadableNum is set (has been assigned a value) and false otherwise */
  public boolean isSetMediaLastReadableNum() {
    return this.mediaLastReadableNum != null;
  }

  public void setMediaLastReadableNumIsSet(boolean value) {
    if (!value) {
      this.mediaLastReadableNum = null;
    }
  }

  public String getMediaLastUpdateTime() {
    return this.mediaLastUpdateTime;
  }

  public MediaWithClient setMediaLastUpdateTime(String mediaLastUpdateTime) {
    this.mediaLastUpdateTime = mediaLastUpdateTime;
    return this;
  }

  public void unsetMediaLastUpdateTime() {
    this.mediaLastUpdateTime = null;
  }

  /** Returns true if field mediaLastUpdateTime is set (has been assigned a value) and false otherwise */
  public boolean isSetMediaLastUpdateTime() {
    return this.mediaLastUpdateTime != null;
  }

  public void setMediaLastUpdateTimeIsSet(boolean value) {
    if (!value) {
      this.mediaLastUpdateTime = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case MEDIA_ID:
      if (value == null) {
        unsetMediaId();
      } else {
        setMediaId((Integer)value);
      }
      break;

    case CLIENT_TYPE:
      if (value == null) {
        unsetClientType();
      } else {
        setClientType((String)value);
      }
      break;

    case MEDIA_LAST_NUM:
      if (value == null) {
        unsetMediaLastNum();
      } else {
        setMediaLastNum((Integer)value);
      }
      break;

    case MEDIA_LAST_READABLE_NUM:
      if (value == null) {
        unsetMediaLastReadableNum();
      } else {
        setMediaLastReadableNum((String)value);
      }
      break;

    case MEDIA_LAST_UPDATE_TIME:
      if (value == null) {
        unsetMediaLastUpdateTime();
      } else {
        setMediaLastUpdateTime((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case MEDIA_ID:
      return Integer.valueOf(getMediaId());

    case CLIENT_TYPE:
      return getClientType();

    case MEDIA_LAST_NUM:
      return Integer.valueOf(getMediaLastNum());

    case MEDIA_LAST_READABLE_NUM:
      return getMediaLastReadableNum();

    case MEDIA_LAST_UPDATE_TIME:
      return getMediaLastUpdateTime();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case MEDIA_ID:
      return isSetMediaId();
    case CLIENT_TYPE:
      return isSetClientType();
    case MEDIA_LAST_NUM:
      return isSetMediaLastNum();
    case MEDIA_LAST_READABLE_NUM:
      return isSetMediaLastReadableNum();
    case MEDIA_LAST_UPDATE_TIME:
      return isSetMediaLastUpdateTime();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof MediaWithClient)
      return this.equals((MediaWithClient)that);
    return false;
  }

  public boolean equals(MediaWithClient that) {
    if (that == null)
      return false;

    boolean this_present_mediaId = true;
    boolean that_present_mediaId = true;
    if (this_present_mediaId || that_present_mediaId) {
      if (!(this_present_mediaId && that_present_mediaId))
        return false;
      if (this.mediaId != that.mediaId)
        return false;
    }

    boolean this_present_clientType = true && this.isSetClientType();
    boolean that_present_clientType = true && that.isSetClientType();
    if (this_present_clientType || that_present_clientType) {
      if (!(this_present_clientType && that_present_clientType))
        return false;
      if (!this.clientType.equals(that.clientType))
        return false;
    }

    boolean this_present_mediaLastNum = true;
    boolean that_present_mediaLastNum = true;
    if (this_present_mediaLastNum || that_present_mediaLastNum) {
      if (!(this_present_mediaLastNum && that_present_mediaLastNum))
        return false;
      if (this.mediaLastNum != that.mediaLastNum)
        return false;
    }

    boolean this_present_mediaLastReadableNum = true && this.isSetMediaLastReadableNum();
    boolean that_present_mediaLastReadableNum = true && that.isSetMediaLastReadableNum();
    if (this_present_mediaLastReadableNum || that_present_mediaLastReadableNum) {
      if (!(this_present_mediaLastReadableNum && that_present_mediaLastReadableNum))
        return false;
      if (!this.mediaLastReadableNum.equals(that.mediaLastReadableNum))
        return false;
    }

    boolean this_present_mediaLastUpdateTime = true && this.isSetMediaLastUpdateTime();
    boolean that_present_mediaLastUpdateTime = true && that.isSetMediaLastUpdateTime();
    if (this_present_mediaLastUpdateTime || that_present_mediaLastUpdateTime) {
      if (!(this_present_mediaLastUpdateTime && that_present_mediaLastUpdateTime))
        return false;
      if (!this.mediaLastUpdateTime.equals(that.mediaLastUpdateTime))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(MediaWithClient other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    MediaWithClient typedOther = (MediaWithClient)other;

    lastComparison = Boolean.valueOf(isSetMediaId()).compareTo(typedOther.isSetMediaId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMediaId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.mediaId, typedOther.mediaId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetClientType()).compareTo(typedOther.isSetClientType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetClientType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.clientType, typedOther.clientType);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetMediaLastNum()).compareTo(typedOther.isSetMediaLastNum());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMediaLastNum()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.mediaLastNum, typedOther.mediaLastNum);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetMediaLastReadableNum()).compareTo(typedOther.isSetMediaLastReadableNum());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMediaLastReadableNum()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.mediaLastReadableNum, typedOther.mediaLastReadableNum);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetMediaLastUpdateTime()).compareTo(typedOther.isSetMediaLastUpdateTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMediaLastUpdateTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.mediaLastUpdateTime, typedOther.mediaLastUpdateTime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("MediaWithClient(");
    boolean first = true;

    sb.append("mediaId:");
    sb.append(this.mediaId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("clientType:");
    if (this.clientType == null) {
      sb.append("null");
    } else {
      sb.append(this.clientType);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("mediaLastNum:");
    sb.append(this.mediaLastNum);
    first = false;
    if (!first) sb.append(", ");
    sb.append("mediaLastReadableNum:");
    if (this.mediaLastReadableNum == null) {
      sb.append("null");
    } else {
      sb.append(this.mediaLastReadableNum);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("mediaLastUpdateTime:");
    if (this.mediaLastUpdateTime == null) {
      sb.append("null");
    } else {
      sb.append(this.mediaLastUpdateTime);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class MediaWithClientStandardSchemeFactory implements SchemeFactory {
    public MediaWithClientStandardScheme getScheme() {
      return new MediaWithClientStandardScheme();
    }
  }

  private static class MediaWithClientStandardScheme extends StandardScheme<MediaWithClient> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, MediaWithClient struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // MEDIA_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.mediaId = iprot.readI32();
              struct.setMediaIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // CLIENT_TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.clientType = iprot.readString();
              struct.setClientTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // MEDIA_LAST_NUM
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.mediaLastNum = iprot.readI32();
              struct.setMediaLastNumIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // MEDIA_LAST_READABLE_NUM
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.mediaLastReadableNum = iprot.readString();
              struct.setMediaLastReadableNumIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // MEDIA_LAST_UPDATE_TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.mediaLastUpdateTime = iprot.readString();
              struct.setMediaLastUpdateTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, MediaWithClient struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(MEDIA_ID_FIELD_DESC);
      oprot.writeI32(struct.mediaId);
      oprot.writeFieldEnd();
      if (struct.clientType != null) {
        oprot.writeFieldBegin(CLIENT_TYPE_FIELD_DESC);
        oprot.writeString(struct.clientType);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(MEDIA_LAST_NUM_FIELD_DESC);
      oprot.writeI32(struct.mediaLastNum);
      oprot.writeFieldEnd();
      if (struct.mediaLastReadableNum != null) {
        oprot.writeFieldBegin(MEDIA_LAST_READABLE_NUM_FIELD_DESC);
        oprot.writeString(struct.mediaLastReadableNum);
        oprot.writeFieldEnd();
      }
      if (struct.mediaLastUpdateTime != null) {
        oprot.writeFieldBegin(MEDIA_LAST_UPDATE_TIME_FIELD_DESC);
        oprot.writeString(struct.mediaLastUpdateTime);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class MediaWithClientTupleSchemeFactory implements SchemeFactory {
    public MediaWithClientTupleScheme getScheme() {
      return new MediaWithClientTupleScheme();
    }
  }

  private static class MediaWithClientTupleScheme extends TupleScheme<MediaWithClient> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, MediaWithClient struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetMediaId()) {
        optionals.set(0);
      }
      if (struct.isSetClientType()) {
        optionals.set(1);
      }
      if (struct.isSetMediaLastNum()) {
        optionals.set(2);
      }
      if (struct.isSetMediaLastReadableNum()) {
        optionals.set(3);
      }
      if (struct.isSetMediaLastUpdateTime()) {
        optionals.set(4);
      }
      oprot.writeBitSet(optionals, 5);
      if (struct.isSetMediaId()) {
        oprot.writeI32(struct.mediaId);
      }
      if (struct.isSetClientType()) {
        oprot.writeString(struct.clientType);
      }
      if (struct.isSetMediaLastNum()) {
        oprot.writeI32(struct.mediaLastNum);
      }
      if (struct.isSetMediaLastReadableNum()) {
        oprot.writeString(struct.mediaLastReadableNum);
      }
      if (struct.isSetMediaLastUpdateTime()) {
        oprot.writeString(struct.mediaLastUpdateTime);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, MediaWithClient struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(5);
      if (incoming.get(0)) {
        struct.mediaId = iprot.readI32();
        struct.setMediaIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.clientType = iprot.readString();
        struct.setClientTypeIsSet(true);
      }
      if (incoming.get(2)) {
        struct.mediaLastNum = iprot.readI32();
        struct.setMediaLastNumIsSet(true);
      }
      if (incoming.get(3)) {
        struct.mediaLastReadableNum = iprot.readString();
        struct.setMediaLastReadableNumIsSet(true);
      }
      if (incoming.get(4)) {
        struct.mediaLastUpdateTime = iprot.readString();
        struct.setMediaLastUpdateTimeIsSet(true);
      }
    }
  }

}

