/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.funshion.search.videolet.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class VideoletResult implements org.apache.thrift.TBase<VideoletResult, VideoletResult._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("VideoletResult");

  private static final org.apache.thrift.protocol.TField VIDEOID_FIELD_DESC = new org.apache.thrift.protocol.TField("videoid", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField VIDEOTYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("videotype", org.apache.thrift.protocol.TType.I32, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new VideoletResultStandardSchemeFactory());
    schemes.put(TupleScheme.class, new VideoletResultTupleSchemeFactory());
  }

  public int videoid; // required
  public int videotype; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    VIDEOID((short)1, "videoid"),
    VIDEOTYPE((short)2, "videotype");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // VIDEOID
          return VIDEOID;
        case 2: // VIDEOTYPE
          return VIDEOTYPE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __VIDEOID_ISSET_ID = 0;
  private static final int __VIDEOTYPE_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.VIDEOID, new org.apache.thrift.meta_data.FieldMetaData("videoid", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.VIDEOTYPE, new org.apache.thrift.meta_data.FieldMetaData("videotype", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(VideoletResult.class, metaDataMap);
  }

  public VideoletResult() {
  }

  public VideoletResult(
    int videoid,
    int videotype)
  {
    this();
    this.videoid = videoid;
    setVideoidIsSet(true);
    this.videotype = videotype;
    setVideotypeIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public VideoletResult(VideoletResult other) {
    __isset_bitfield = other.__isset_bitfield;
    this.videoid = other.videoid;
    this.videotype = other.videotype;
  }

  public VideoletResult deepCopy() {
    return new VideoletResult(this);
  }

  @Override
  public void clear() {
    setVideoidIsSet(false);
    this.videoid = 0;
    setVideotypeIsSet(false);
    this.videotype = 0;
  }

  public int getVideoid() {
    return this.videoid;
  }

  public VideoletResult setVideoid(int videoid) {
    this.videoid = videoid;
    setVideoidIsSet(true);
    return this;
  }

  public void unsetVideoid() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __VIDEOID_ISSET_ID);
  }

  /** Returns true if field videoid is set (has been assigned a value) and false otherwise */
  public boolean isSetVideoid() {
    return EncodingUtils.testBit(__isset_bitfield, __VIDEOID_ISSET_ID);
  }

  public void setVideoidIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __VIDEOID_ISSET_ID, value);
  }

  public int getVideotype() {
    return this.videotype;
  }

  public VideoletResult setVideotype(int videotype) {
    this.videotype = videotype;
    setVideotypeIsSet(true);
    return this;
  }

  public void unsetVideotype() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __VIDEOTYPE_ISSET_ID);
  }

  /** Returns true if field videotype is set (has been assigned a value) and false otherwise */
  public boolean isSetVideotype() {
    return EncodingUtils.testBit(__isset_bitfield, __VIDEOTYPE_ISSET_ID);
  }

  public void setVideotypeIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __VIDEOTYPE_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case VIDEOID:
      if (value == null) {
        unsetVideoid();
      } else {
        setVideoid((Integer)value);
      }
      break;

    case VIDEOTYPE:
      if (value == null) {
        unsetVideotype();
      } else {
        setVideotype((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case VIDEOID:
      return Integer.valueOf(getVideoid());

    case VIDEOTYPE:
      return Integer.valueOf(getVideotype());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case VIDEOID:
      return isSetVideoid();
    case VIDEOTYPE:
      return isSetVideotype();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof VideoletResult)
      return this.equals((VideoletResult)that);
    return false;
  }

  public boolean equals(VideoletResult that) {
    if (that == null)
      return false;

    boolean this_present_videoid = true;
    boolean that_present_videoid = true;
    if (this_present_videoid || that_present_videoid) {
      if (!(this_present_videoid && that_present_videoid))
        return false;
      if (this.videoid != that.videoid)
        return false;
    }

    boolean this_present_videotype = true;
    boolean that_present_videotype = true;
    if (this_present_videotype || that_present_videotype) {
      if (!(this_present_videotype && that_present_videotype))
        return false;
      if (this.videotype != that.videotype)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(VideoletResult other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    VideoletResult typedOther = (VideoletResult)other;

    lastComparison = Boolean.valueOf(isSetVideoid()).compareTo(typedOther.isSetVideoid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetVideoid()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.videoid, typedOther.videoid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetVideotype()).compareTo(typedOther.isSetVideotype());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetVideotype()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.videotype, typedOther.videotype);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("VideoletResult(");
    boolean first = true;

    sb.append("videoid:");
    sb.append(this.videoid);
    first = false;
    if (!first) sb.append(", ");
    sb.append("videotype:");
    sb.append(this.videotype);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class VideoletResultStandardSchemeFactory implements SchemeFactory {
    public VideoletResultStandardScheme getScheme() {
      return new VideoletResultStandardScheme();
    }
  }

  private static class VideoletResultStandardScheme extends StandardScheme<VideoletResult> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, VideoletResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // VIDEOID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.videoid = iprot.readI32();
              struct.setVideoidIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // VIDEOTYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.videotype = iprot.readI32();
              struct.setVideotypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, VideoletResult struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(VIDEOID_FIELD_DESC);
      oprot.writeI32(struct.videoid);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(VIDEOTYPE_FIELD_DESC);
      oprot.writeI32(struct.videotype);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class VideoletResultTupleSchemeFactory implements SchemeFactory {
    public VideoletResultTupleScheme getScheme() {
      return new VideoletResultTupleScheme();
    }
  }

  private static class VideoletResultTupleScheme extends TupleScheme<VideoletResult> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, VideoletResult struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetVideoid()) {
        optionals.set(0);
      }
      if (struct.isSetVideotype()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetVideoid()) {
        oprot.writeI32(struct.videoid);
      }
      if (struct.isSetVideotype()) {
        oprot.writeI32(struct.videotype);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, VideoletResult struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.videoid = iprot.readI32();
        struct.setVideoidIsSet(true);
      }
      if (incoming.get(1)) {
        struct.videotype = iprot.readI32();
        struct.setVideotypeIsSet(true);
      }
    }
  }

}

