/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.funshion.ucs.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum RetCode implements org.apache.thrift.TEnum {
  OK(200),
  BadReq(400),
  UnAuth(401),
  NotFound(404),
  LenRequire(411),
  EntTooLarge(413),
  URITooLong(414),
  Busy(430),
  SrvErr(500),
  SrvUnavail(503),
  GateTimeout(504);

  private final int value;

  private RetCode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static RetCode findByValue(int value) { 
    switch (value) {
      case 200:
        return OK;
      case 400:
        return BadReq;
      case 401:
        return UnAuth;
      case 404:
        return NotFound;
      case 411:
        return LenRequire;
      case 413:
        return EntTooLarge;
      case 414:
        return URITooLong;
      case 430:
        return Busy;
      case 500:
        return SrvErr;
      case 503:
        return SrvUnavail;
      case 504:
        return GateTimeout;
      default:
        return null;
    }
  }
}
