package com.funshion.gamma.mediaExtend.thrift;
/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Behind implements org.apache.thrift.TBase<Behind, Behind._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Behind");

  private static final org.apache.thrift.protocol.TField MEDIA_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("mediaId", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField BEHIND_FIELD_DESC = new org.apache.thrift.protocol.TField("behind", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new BehindStandardSchemeFactory());
    schemes.put(TupleScheme.class, new BehindTupleSchemeFactory());
  }

  public int mediaId; // required
  public String behind; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    MEDIA_ID((short)1, "mediaId"),
    BEHIND((short)2, "behind");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // MEDIA_ID
          return MEDIA_ID;
        case 2: // BEHIND
          return BEHIND;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __MEDIAID_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.MEDIA_ID, new org.apache.thrift.meta_data.FieldMetaData("mediaId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.BEHIND, new org.apache.thrift.meta_data.FieldMetaData("behind", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Behind.class, metaDataMap);
  }

  public Behind() {
  }

  public Behind(
    int mediaId,
    String behind)
  {
    this();
    this.mediaId = mediaId;
    setMediaIdIsSet(true);
    this.behind = behind;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Behind(Behind other) {
    __isset_bitfield = other.__isset_bitfield;
    this.mediaId = other.mediaId;
    if (other.isSetBehind()) {
      this.behind = other.behind;
    }
  }

  public Behind deepCopy() {
    return new Behind(this);
  }

  @Override
  public void clear() {
    setMediaIdIsSet(false);
    this.mediaId = 0;
    this.behind = null;
  }

  public int getMediaId() {
    return this.mediaId;
  }

  public Behind setMediaId(int mediaId) {
    this.mediaId = mediaId;
    setMediaIdIsSet(true);
    return this;
  }

  public void unsetMediaId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __MEDIAID_ISSET_ID);
  }

  /** Returns true if field mediaId is set (has been assigned a value) and false otherwise */
  public boolean isSetMediaId() {
    return EncodingUtils.testBit(__isset_bitfield, __MEDIAID_ISSET_ID);
  }

  public void setMediaIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __MEDIAID_ISSET_ID, value);
  }

  public String getBehind() {
    return this.behind;
  }

  public Behind setBehind(String behind) {
    this.behind = behind;
    return this;
  }

  public void unsetBehind() {
    this.behind = null;
  }

  /** Returns true if field behind is set (has been assigned a value) and false otherwise */
  public boolean isSetBehind() {
    return this.behind != null;
  }

  public void setBehindIsSet(boolean value) {
    if (!value) {
      this.behind = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case MEDIA_ID:
      if (value == null) {
        unsetMediaId();
      } else {
        setMediaId((Integer)value);
      }
      break;

    case BEHIND:
      if (value == null) {
        unsetBehind();
      } else {
        setBehind((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case MEDIA_ID:
      return Integer.valueOf(getMediaId());

    case BEHIND:
      return getBehind();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case MEDIA_ID:
      return isSetMediaId();
    case BEHIND:
      return isSetBehind();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof Behind)
      return this.equals((Behind)that);
    return false;
  }

  public boolean equals(Behind that) {
    if (that == null)
      return false;

    boolean this_present_mediaId = true;
    boolean that_present_mediaId = true;
    if (this_present_mediaId || that_present_mediaId) {
      if (!(this_present_mediaId && that_present_mediaId))
        return false;
      if (this.mediaId != that.mediaId)
        return false;
    }

    boolean this_present_behind = true && this.isSetBehind();
    boolean that_present_behind = true && that.isSetBehind();
    if (this_present_behind || that_present_behind) {
      if (!(this_present_behind && that_present_behind))
        return false;
      if (!this.behind.equals(that.behind))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(Behind other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    Behind typedOther = (Behind)other;

    lastComparison = Boolean.valueOf(isSetMediaId()).compareTo(typedOther.isSetMediaId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMediaId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.mediaId, typedOther.mediaId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetBehind()).compareTo(typedOther.isSetBehind());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBehind()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.behind, typedOther.behind);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Behind(");
    boolean first = true;

    sb.append("mediaId:");
    sb.append(this.mediaId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("behind:");
    if (this.behind == null) {
      sb.append("null");
    } else {
      sb.append(this.behind);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class BehindStandardSchemeFactory implements SchemeFactory {
    public BehindStandardScheme getScheme() {
      return new BehindStandardScheme();
    }
  }

  private static class BehindStandardScheme extends StandardScheme<Behind> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Behind struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // MEDIA_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.mediaId = iprot.readI32();
              struct.setMediaIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // BEHIND
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.behind = iprot.readString();
              struct.setBehindIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Behind struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(MEDIA_ID_FIELD_DESC);
      oprot.writeI32(struct.mediaId);
      oprot.writeFieldEnd();
      if (struct.behind != null) {
        oprot.writeFieldBegin(BEHIND_FIELD_DESC);
        oprot.writeString(struct.behind);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class BehindTupleSchemeFactory implements SchemeFactory {
    public BehindTupleScheme getScheme() {
      return new BehindTupleScheme();
    }
  }

  private static class BehindTupleScheme extends TupleScheme<Behind> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Behind struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetMediaId()) {
        optionals.set(0);
      }
      if (struct.isSetBehind()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetMediaId()) {
        oprot.writeI32(struct.mediaId);
      }
      if (struct.isSetBehind()) {
        oprot.writeString(struct.behind);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Behind struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.mediaId = iprot.readI32();
        struct.setMediaIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.behind = iprot.readString();
        struct.setBehindIsSet(true);
      }
    }
  }

}

