package com.funshion.gamma.mediaExtend.thrift;
/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class MediaExtendService {

  public interface Iface {

    public List<Plots> getPlotsByMediaIds(List<Integer> mediaIds) throws org.apache.thrift.TException;

    public List<Behind> getBehindByMediaIds(List<Integer> mediaIds) throws org.apache.thrift.TException;

  }

  public interface AsyncIface {

    public void getPlotsByMediaIds(List<Integer> mediaIds, org.apache.thrift.async.AsyncMethodCallback<AsyncClient.getPlotsByMediaIds_call> resultHandler) throws org.apache.thrift.TException;

    public void getBehindByMediaIds(List<Integer> mediaIds, org.apache.thrift.async.AsyncMethodCallback<AsyncClient.getBehindByMediaIds_call> resultHandler) throws org.apache.thrift.TException;

  }

  public static class Client extends org.apache.thrift.TServiceClient implements Iface {
    public static class Factory implements org.apache.thrift.TServiceClientFactory<Client> {
      public Factory() {}
      public Client getClient(org.apache.thrift.protocol.TProtocol prot) {
        return new Client(prot);
      }
      public Client getClient(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
        return new Client(iprot, oprot);
      }
    }

    public Client(org.apache.thrift.protocol.TProtocol prot)
    {
      super(prot, prot);
    }

    public Client(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
      super(iprot, oprot);
    }

    public List<Plots> getPlotsByMediaIds(List<Integer> mediaIds) throws org.apache.thrift.TException
    {
      send_getPlotsByMediaIds(mediaIds);
      return recv_getPlotsByMediaIds();
    }

    public void send_getPlotsByMediaIds(List<Integer> mediaIds) throws org.apache.thrift.TException
    {
      getPlotsByMediaIds_args args = new getPlotsByMediaIds_args();
      args.setMediaIds(mediaIds);
      sendBase("getPlotsByMediaIds", args);
    }

    public List<Plots> recv_getPlotsByMediaIds() throws org.apache.thrift.TException
    {
      getPlotsByMediaIds_result result = new getPlotsByMediaIds_result();
      receiveBase(result, "getPlotsByMediaIds");
      if (result.isSetSuccess()) {
        return result.success;
      }
      throw new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.MISSING_RESULT, "getPlotsByMediaIds failed: unknown result");
    }

    public List<Behind> getBehindByMediaIds(List<Integer> mediaIds) throws org.apache.thrift.TException
    {
      send_getBehindByMediaIds(mediaIds);
      return recv_getBehindByMediaIds();
    }

    public void send_getBehindByMediaIds(List<Integer> mediaIds) throws org.apache.thrift.TException
    {
      getBehindByMediaIds_args args = new getBehindByMediaIds_args();
      args.setMediaIds(mediaIds);
      sendBase("getBehindByMediaIds", args);
    }

    public List<Behind> recv_getBehindByMediaIds() throws org.apache.thrift.TException
    {
      getBehindByMediaIds_result result = new getBehindByMediaIds_result();
      receiveBase(result, "getBehindByMediaIds");
      if (result.isSetSuccess()) {
        return result.success;
      }
      throw new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.MISSING_RESULT, "getBehindByMediaIds failed: unknown result");
    }

  }
  public static class AsyncClient extends org.apache.thrift.async.TAsyncClient implements AsyncIface {
    public static class Factory implements org.apache.thrift.async.TAsyncClientFactory<AsyncClient> {
      private org.apache.thrift.async.TAsyncClientManager clientManager;
      private org.apache.thrift.protocol.TProtocolFactory protocolFactory;
      public Factory(org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.protocol.TProtocolFactory protocolFactory) {
        this.clientManager = clientManager;
        this.protocolFactory = protocolFactory;
      }
      public AsyncClient getAsyncClient(org.apache.thrift.transport.TNonblockingTransport transport) {
        return new AsyncClient(protocolFactory, clientManager, transport);
      }
    }

    public AsyncClient(org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.transport.TNonblockingTransport transport) {
      super(protocolFactory, clientManager, transport);
    }

    public void getPlotsByMediaIds(List<Integer> mediaIds, org.apache.thrift.async.AsyncMethodCallback<getPlotsByMediaIds_call> resultHandler) throws org.apache.thrift.TException {
      checkReady();
      getPlotsByMediaIds_call method_call = new getPlotsByMediaIds_call(mediaIds, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class getPlotsByMediaIds_call extends org.apache.thrift.async.TAsyncMethodCall {
      private List<Integer> mediaIds;
      public getPlotsByMediaIds_call(List<Integer> mediaIds, org.apache.thrift.async.AsyncMethodCallback<getPlotsByMediaIds_call> resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException {
        super(client, protocolFactory, transport, resultHandler, false);
        this.mediaIds = mediaIds;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("getPlotsByMediaIds", org.apache.thrift.protocol.TMessageType.CALL, 0));
        getPlotsByMediaIds_args args = new getPlotsByMediaIds_args();
        args.setMediaIds(mediaIds);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public List<Plots> getResult() throws org.apache.thrift.TException {
        if (getState() != org.apache.thrift.async.TAsyncMethodCall.State.RESPONSE_READ) {
          throw new IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        return (new Client(prot)).recv_getPlotsByMediaIds();
      }
    }

    public void getBehindByMediaIds(List<Integer> mediaIds, org.apache.thrift.async.AsyncMethodCallback<getBehindByMediaIds_call> resultHandler) throws org.apache.thrift.TException {
      checkReady();
      getBehindByMediaIds_call method_call = new getBehindByMediaIds_call(mediaIds, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class getBehindByMediaIds_call extends org.apache.thrift.async.TAsyncMethodCall {
      private List<Integer> mediaIds;
      public getBehindByMediaIds_call(List<Integer> mediaIds, org.apache.thrift.async.AsyncMethodCallback<getBehindByMediaIds_call> resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException {
        super(client, protocolFactory, transport, resultHandler, false);
        this.mediaIds = mediaIds;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("getBehindByMediaIds", org.apache.thrift.protocol.TMessageType.CALL, 0));
        getBehindByMediaIds_args args = new getBehindByMediaIds_args();
        args.setMediaIds(mediaIds);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public List<Behind> getResult() throws org.apache.thrift.TException {
        if (getState() != org.apache.thrift.async.TAsyncMethodCall.State.RESPONSE_READ) {
          throw new IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        return (new Client(prot)).recv_getBehindByMediaIds();
      }
    }

  }

  public static class Processor<I extends Iface> extends org.apache.thrift.TBaseProcessor<I> implements org.apache.thrift.TProcessor {
    private static final Logger LOGGER = LoggerFactory.getLogger(Processor.class.getName());
    public Processor(I iface) {
      super(iface, getProcessMap(new HashMap<String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>>()));
    }

    protected Processor(I iface, Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends Iface> Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> getProcessMap(Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      processMap.put("getPlotsByMediaIds", new getPlotsByMediaIds());
      processMap.put("getBehindByMediaIds", new getBehindByMediaIds());
      return processMap;
    }

    public static class getPlotsByMediaIds<I extends Iface> extends org.apache.thrift.ProcessFunction<I, getPlotsByMediaIds_args> {
      public getPlotsByMediaIds() {
        super("getPlotsByMediaIds");
      }

      public getPlotsByMediaIds_args getEmptyArgsInstance() {
        return new getPlotsByMediaIds_args();
      }

      protected boolean isOneway() {
        return false;
      }

      public getPlotsByMediaIds_result getResult(I iface, getPlotsByMediaIds_args args) throws org.apache.thrift.TException {
        getPlotsByMediaIds_result result = new getPlotsByMediaIds_result();
        result.success = iface.getPlotsByMediaIds(args.mediaIds);
        return result;
      }
    }

    public static class getBehindByMediaIds<I extends Iface> extends org.apache.thrift.ProcessFunction<I, getBehindByMediaIds_args> {
      public getBehindByMediaIds() {
        super("getBehindByMediaIds");
      }

      public getBehindByMediaIds_args getEmptyArgsInstance() {
        return new getBehindByMediaIds_args();
      }

      protected boolean isOneway() {
        return false;
      }

      public getBehindByMediaIds_result getResult(I iface, getBehindByMediaIds_args args) throws org.apache.thrift.TException {
        getBehindByMediaIds_result result = new getBehindByMediaIds_result();
        result.success = iface.getBehindByMediaIds(args.mediaIds);
        return result;
      }
    }

  }

  public static class getPlotsByMediaIds_args implements org.apache.thrift.TBase<getPlotsByMediaIds_args, getPlotsByMediaIds_args._Fields>, java.io.Serializable, Cloneable   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("getPlotsByMediaIds_args");

    private static final org.apache.thrift.protocol.TField MEDIA_IDS_FIELD_DESC = new org.apache.thrift.protocol.TField("mediaIds", org.apache.thrift.protocol.TType.LIST, (short)1);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new getPlotsByMediaIds_argsStandardSchemeFactory());
      schemes.put(TupleScheme.class, new getPlotsByMediaIds_argsTupleSchemeFactory());
    }

    public List<Integer> mediaIds; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      MEDIA_IDS((short)1, "mediaIds");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // MEDIA_IDS
            return MEDIA_IDS;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.MEDIA_IDS, new org.apache.thrift.meta_data.FieldMetaData("mediaIds", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
              new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32))));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(getPlotsByMediaIds_args.class, metaDataMap);
    }

    public getPlotsByMediaIds_args() {
    }

    public getPlotsByMediaIds_args(
      List<Integer> mediaIds)
    {
      this();
      this.mediaIds = mediaIds;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public getPlotsByMediaIds_args(getPlotsByMediaIds_args other) {
      if (other.isSetMediaIds()) {
        List<Integer> __this__mediaIds = new ArrayList<Integer>();
        for (Integer other_element : other.mediaIds) {
          __this__mediaIds.add(other_element);
        }
        this.mediaIds = __this__mediaIds;
      }
    }

    public getPlotsByMediaIds_args deepCopy() {
      return new getPlotsByMediaIds_args(this);
    }

    @Override
    public void clear() {
      this.mediaIds = null;
    }

    public int getMediaIdsSize() {
      return (this.mediaIds == null) ? 0 : this.mediaIds.size();
    }

    public java.util.Iterator<Integer> getMediaIdsIterator() {
      return (this.mediaIds == null) ? null : this.mediaIds.iterator();
    }

    public void addToMediaIds(int elem) {
      if (this.mediaIds == null) {
        this.mediaIds = new ArrayList<Integer>();
      }
      this.mediaIds.add(elem);
    }

    public List<Integer> getMediaIds() {
      return this.mediaIds;
    }

    public getPlotsByMediaIds_args setMediaIds(List<Integer> mediaIds) {
      this.mediaIds = mediaIds;
      return this;
    }

    public void unsetMediaIds() {
      this.mediaIds = null;
    }

    /** Returns true if field mediaIds is set (has been assigned a value) and false otherwise */
    public boolean isSetMediaIds() {
      return this.mediaIds != null;
    }

    public void setMediaIdsIsSet(boolean value) {
      if (!value) {
        this.mediaIds = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case MEDIA_IDS:
        if (value == null) {
          unsetMediaIds();
        } else {
          setMediaIds((List<Integer>)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case MEDIA_IDS:
        return getMediaIds();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case MEDIA_IDS:
        return isSetMediaIds();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof getPlotsByMediaIds_args)
        return this.equals((getPlotsByMediaIds_args)that);
      return false;
    }

    public boolean equals(getPlotsByMediaIds_args that) {
      if (that == null)
        return false;

      boolean this_present_mediaIds = true && this.isSetMediaIds();
      boolean that_present_mediaIds = true && that.isSetMediaIds();
      if (this_present_mediaIds || that_present_mediaIds) {
        if (!(this_present_mediaIds && that_present_mediaIds))
          return false;
        if (!this.mediaIds.equals(that.mediaIds))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      return 0;
    }

    public int compareTo(getPlotsByMediaIds_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;
      getPlotsByMediaIds_args typedOther = (getPlotsByMediaIds_args)other;

      lastComparison = Boolean.valueOf(isSetMediaIds()).compareTo(typedOther.isSetMediaIds());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetMediaIds()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.mediaIds, typedOther.mediaIds);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("getPlotsByMediaIds_args(");
      boolean first = true;

      sb.append("mediaIds:");
      if (this.mediaIds == null) {
        sb.append("null");
      } else {
        sb.append(this.mediaIds);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class getPlotsByMediaIds_argsStandardSchemeFactory implements SchemeFactory {
      public getPlotsByMediaIds_argsStandardScheme getScheme() {
        return new getPlotsByMediaIds_argsStandardScheme();
      }
    }

    private static class getPlotsByMediaIds_argsStandardScheme extends StandardScheme<getPlotsByMediaIds_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, getPlotsByMediaIds_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // MEDIA_IDS
              if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
                {
                  org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                  struct.mediaIds = new ArrayList<Integer>(_list0.size);
                  for (int _i1 = 0; _i1 < _list0.size; ++_i1)
                  {
                    int _elem2; // required
                    _elem2 = iprot.readI32();
                    struct.mediaIds.add(_elem2);
                  }
                  iprot.readListEnd();
                }
                struct.setMediaIdsIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, getPlotsByMediaIds_args struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.mediaIds != null) {
          oprot.writeFieldBegin(MEDIA_IDS_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I32, struct.mediaIds.size()));
            for (int _iter3 : struct.mediaIds)
            {
              oprot.writeI32(_iter3);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class getPlotsByMediaIds_argsTupleSchemeFactory implements SchemeFactory {
      public getPlotsByMediaIds_argsTupleScheme getScheme() {
        return new getPlotsByMediaIds_argsTupleScheme();
      }
    }

    private static class getPlotsByMediaIds_argsTupleScheme extends TupleScheme<getPlotsByMediaIds_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, getPlotsByMediaIds_args struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetMediaIds()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetMediaIds()) {
          {
            oprot.writeI32(struct.mediaIds.size());
            for (int _iter4 : struct.mediaIds)
            {
              oprot.writeI32(_iter4);
            }
          }
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, getPlotsByMediaIds_args struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          {
            org.apache.thrift.protocol.TList _list5 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I32, iprot.readI32());
            struct.mediaIds = new ArrayList<Integer>(_list5.size);
            for (int _i6 = 0; _i6 < _list5.size; ++_i6)
            {
              int _elem7; // required
              _elem7 = iprot.readI32();
              struct.mediaIds.add(_elem7);
            }
          }
          struct.setMediaIdsIsSet(true);
        }
      }
    }

  }

  public static class getPlotsByMediaIds_result implements org.apache.thrift.TBase<getPlotsByMediaIds_result, getPlotsByMediaIds_result._Fields>, java.io.Serializable, Cloneable   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("getPlotsByMediaIds_result");

    private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.LIST, (short)0);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new getPlotsByMediaIds_resultStandardSchemeFactory());
      schemes.put(TupleScheme.class, new getPlotsByMediaIds_resultTupleSchemeFactory());
    }

    public List<Plots> success; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SUCCESS((short)0, "success");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 0: // SUCCESS
            return SUCCESS;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
              new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Plots.class))));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(getPlotsByMediaIds_result.class, metaDataMap);
    }

    public getPlotsByMediaIds_result() {
    }

    public getPlotsByMediaIds_result(
      List<Plots> success)
    {
      this();
      this.success = success;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public getPlotsByMediaIds_result(getPlotsByMediaIds_result other) {
      if (other.isSetSuccess()) {
        List<Plots> __this__success = new ArrayList<Plots>();
        for (Plots other_element : other.success) {
          __this__success.add(new Plots(other_element));
        }
        this.success = __this__success;
      }
    }

    public getPlotsByMediaIds_result deepCopy() {
      return new getPlotsByMediaIds_result(this);
    }

    @Override
    public void clear() {
      this.success = null;
    }

    public int getSuccessSize() {
      return (this.success == null) ? 0 : this.success.size();
    }

    public java.util.Iterator<Plots> getSuccessIterator() {
      return (this.success == null) ? null : this.success.iterator();
    }

    public void addToSuccess(Plots elem) {
      if (this.success == null) {
        this.success = new ArrayList<Plots>();
      }
      this.success.add(elem);
    }

    public List<Plots> getSuccess() {
      return this.success;
    }

    public getPlotsByMediaIds_result setSuccess(List<Plots> success) {
      this.success = success;
      return this;
    }

    public void unsetSuccess() {
      this.success = null;
    }

    /** Returns true if field success is set (has been assigned a value) and false otherwise */
    public boolean isSetSuccess() {
      return this.success != null;
    }

    public void setSuccessIsSet(boolean value) {
      if (!value) {
        this.success = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case SUCCESS:
        if (value == null) {
          unsetSuccess();
        } else {
          setSuccess((List<Plots>)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case SUCCESS:
        return getSuccess();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case SUCCESS:
        return isSetSuccess();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof getPlotsByMediaIds_result)
        return this.equals((getPlotsByMediaIds_result)that);
      return false;
    }

    public boolean equals(getPlotsByMediaIds_result that) {
      if (that == null)
        return false;

      boolean this_present_success = true && this.isSetSuccess();
      boolean that_present_success = true && that.isSetSuccess();
      if (this_present_success || that_present_success) {
        if (!(this_present_success && that_present_success))
          return false;
        if (!this.success.equals(that.success))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      return 0;
    }

    public int compareTo(getPlotsByMediaIds_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;
      getPlotsByMediaIds_result typedOther = (getPlotsByMediaIds_result)other;

      lastComparison = Boolean.valueOf(isSetSuccess()).compareTo(typedOther.isSetSuccess());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSuccess()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, typedOther.success);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
      }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("getPlotsByMediaIds_result(");
      boolean first = true;

      sb.append("success:");
      if (this.success == null) {
        sb.append("null");
      } else {
        sb.append(this.success);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class getPlotsByMediaIds_resultStandardSchemeFactory implements SchemeFactory {
      public getPlotsByMediaIds_resultStandardScheme getScheme() {
        return new getPlotsByMediaIds_resultStandardScheme();
      }
    }

    private static class getPlotsByMediaIds_resultStandardScheme extends StandardScheme<getPlotsByMediaIds_result> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, getPlotsByMediaIds_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 0: // SUCCESS
              if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
                {
                  org.apache.thrift.protocol.TList _list8 = iprot.readListBegin();
                  struct.success = new ArrayList<Plots>(_list8.size);
                  for (int _i9 = 0; _i9 < _list8.size; ++_i9)
                  {
                    Plots _elem10; // required
                    _elem10 = new Plots();
                    _elem10.read(iprot);
                    struct.success.add(_elem10);
                  }
                  iprot.readListEnd();
                }
                struct.setSuccessIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, getPlotsByMediaIds_result struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.success != null) {
          oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.success.size()));
            for (Plots _iter11 : struct.success)
            {
              _iter11.write(oprot);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class getPlotsByMediaIds_resultTupleSchemeFactory implements SchemeFactory {
      public getPlotsByMediaIds_resultTupleScheme getScheme() {
        return new getPlotsByMediaIds_resultTupleScheme();
      }
    }

    private static class getPlotsByMediaIds_resultTupleScheme extends TupleScheme<getPlotsByMediaIds_result> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, getPlotsByMediaIds_result struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetSuccess()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetSuccess()) {
          {
            oprot.writeI32(struct.success.size());
            for (Plots _iter12 : struct.success)
            {
              _iter12.write(oprot);
            }
          }
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, getPlotsByMediaIds_result struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          {
            org.apache.thrift.protocol.TList _list13 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
            struct.success = new ArrayList<Plots>(_list13.size);
            for (int _i14 = 0; _i14 < _list13.size; ++_i14)
            {
              Plots _elem15; // required
              _elem15 = new Plots();
              _elem15.read(iprot);
              struct.success.add(_elem15);
            }
          }
          struct.setSuccessIsSet(true);
        }
      }
    }

  }

  public static class getBehindByMediaIds_args implements org.apache.thrift.TBase<getBehindByMediaIds_args, getBehindByMediaIds_args._Fields>, java.io.Serializable, Cloneable   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("getBehindByMediaIds_args");

    private static final org.apache.thrift.protocol.TField MEDIA_IDS_FIELD_DESC = new org.apache.thrift.protocol.TField("mediaIds", org.apache.thrift.protocol.TType.LIST, (short)1);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new getBehindByMediaIds_argsStandardSchemeFactory());
      schemes.put(TupleScheme.class, new getBehindByMediaIds_argsTupleSchemeFactory());
    }

    public List<Integer> mediaIds; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      MEDIA_IDS((short)1, "mediaIds");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // MEDIA_IDS
            return MEDIA_IDS;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.MEDIA_IDS, new org.apache.thrift.meta_data.FieldMetaData("mediaIds", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
              new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32))));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(getBehindByMediaIds_args.class, metaDataMap);
    }

    public getBehindByMediaIds_args() {
    }

    public getBehindByMediaIds_args(
      List<Integer> mediaIds)
    {
      this();
      this.mediaIds = mediaIds;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public getBehindByMediaIds_args(getBehindByMediaIds_args other) {
      if (other.isSetMediaIds()) {
        List<Integer> __this__mediaIds = new ArrayList<Integer>();
        for (Integer other_element : other.mediaIds) {
          __this__mediaIds.add(other_element);
        }
        this.mediaIds = __this__mediaIds;
      }
    }

    public getBehindByMediaIds_args deepCopy() {
      return new getBehindByMediaIds_args(this);
    }

    @Override
    public void clear() {
      this.mediaIds = null;
    }

    public int getMediaIdsSize() {
      return (this.mediaIds == null) ? 0 : this.mediaIds.size();
    }

    public java.util.Iterator<Integer> getMediaIdsIterator() {
      return (this.mediaIds == null) ? null : this.mediaIds.iterator();
    }

    public void addToMediaIds(int elem) {
      if (this.mediaIds == null) {
        this.mediaIds = new ArrayList<Integer>();
      }
      this.mediaIds.add(elem);
    }

    public List<Integer> getMediaIds() {
      return this.mediaIds;
    }

    public getBehindByMediaIds_args setMediaIds(List<Integer> mediaIds) {
      this.mediaIds = mediaIds;
      return this;
    }

    public void unsetMediaIds() {
      this.mediaIds = null;
    }

    /** Returns true if field mediaIds is set (has been assigned a value) and false otherwise */
    public boolean isSetMediaIds() {
      return this.mediaIds != null;
    }

    public void setMediaIdsIsSet(boolean value) {
      if (!value) {
        this.mediaIds = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case MEDIA_IDS:
        if (value == null) {
          unsetMediaIds();
        } else {
          setMediaIds((List<Integer>)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case MEDIA_IDS:
        return getMediaIds();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case MEDIA_IDS:
        return isSetMediaIds();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof getBehindByMediaIds_args)
        return this.equals((getBehindByMediaIds_args)that);
      return false;
    }

    public boolean equals(getBehindByMediaIds_args that) {
      if (that == null)
        return false;

      boolean this_present_mediaIds = true && this.isSetMediaIds();
      boolean that_present_mediaIds = true && that.isSetMediaIds();
      if (this_present_mediaIds || that_present_mediaIds) {
        if (!(this_present_mediaIds && that_present_mediaIds))
          return false;
        if (!this.mediaIds.equals(that.mediaIds))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      return 0;
    }

    public int compareTo(getBehindByMediaIds_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;
      getBehindByMediaIds_args typedOther = (getBehindByMediaIds_args)other;

      lastComparison = Boolean.valueOf(isSetMediaIds()).compareTo(typedOther.isSetMediaIds());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetMediaIds()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.mediaIds, typedOther.mediaIds);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("getBehindByMediaIds_args(");
      boolean first = true;

      sb.append("mediaIds:");
      if (this.mediaIds == null) {
        sb.append("null");
      } else {
        sb.append(this.mediaIds);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class getBehindByMediaIds_argsStandardSchemeFactory implements SchemeFactory {
      public getBehindByMediaIds_argsStandardScheme getScheme() {
        return new getBehindByMediaIds_argsStandardScheme();
      }
    }

    private static class getBehindByMediaIds_argsStandardScheme extends StandardScheme<getBehindByMediaIds_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, getBehindByMediaIds_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // MEDIA_IDS
              if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
                {
                  org.apache.thrift.protocol.TList _list16 = iprot.readListBegin();
                  struct.mediaIds = new ArrayList<Integer>(_list16.size);
                  for (int _i17 = 0; _i17 < _list16.size; ++_i17)
                  {
                    int _elem18; // required
                    _elem18 = iprot.readI32();
                    struct.mediaIds.add(_elem18);
                  }
                  iprot.readListEnd();
                }
                struct.setMediaIdsIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, getBehindByMediaIds_args struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.mediaIds != null) {
          oprot.writeFieldBegin(MEDIA_IDS_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I32, struct.mediaIds.size()));
            for (int _iter19 : struct.mediaIds)
            {
              oprot.writeI32(_iter19);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class getBehindByMediaIds_argsTupleSchemeFactory implements SchemeFactory {
      public getBehindByMediaIds_argsTupleScheme getScheme() {
        return new getBehindByMediaIds_argsTupleScheme();
      }
    }

    private static class getBehindByMediaIds_argsTupleScheme extends TupleScheme<getBehindByMediaIds_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, getBehindByMediaIds_args struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetMediaIds()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetMediaIds()) {
          {
            oprot.writeI32(struct.mediaIds.size());
            for (int _iter20 : struct.mediaIds)
            {
              oprot.writeI32(_iter20);
            }
          }
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, getBehindByMediaIds_args struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          {
            org.apache.thrift.protocol.TList _list21 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I32, iprot.readI32());
            struct.mediaIds = new ArrayList<Integer>(_list21.size);
            for (int _i22 = 0; _i22 < _list21.size; ++_i22)
            {
              int _elem23; // required
              _elem23 = iprot.readI32();
              struct.mediaIds.add(_elem23);
            }
          }
          struct.setMediaIdsIsSet(true);
        }
      }
    }

  }

  public static class getBehindByMediaIds_result implements org.apache.thrift.TBase<getBehindByMediaIds_result, getBehindByMediaIds_result._Fields>, java.io.Serializable, Cloneable   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("getBehindByMediaIds_result");

    private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.LIST, (short)0);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new getBehindByMediaIds_resultStandardSchemeFactory());
      schemes.put(TupleScheme.class, new getBehindByMediaIds_resultTupleSchemeFactory());
    }

    public List<Behind> success; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SUCCESS((short)0, "success");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 0: // SUCCESS
            return SUCCESS;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
              new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Behind.class))));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(getBehindByMediaIds_result.class, metaDataMap);
    }

    public getBehindByMediaIds_result() {
    }

    public getBehindByMediaIds_result(
      List<Behind> success)
    {
      this();
      this.success = success;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public getBehindByMediaIds_result(getBehindByMediaIds_result other) {
      if (other.isSetSuccess()) {
        List<Behind> __this__success = new ArrayList<Behind>();
        for (Behind other_element : other.success) {
          __this__success.add(new Behind(other_element));
        }
        this.success = __this__success;
      }
    }

    public getBehindByMediaIds_result deepCopy() {
      return new getBehindByMediaIds_result(this);
    }

    @Override
    public void clear() {
      this.success = null;
    }

    public int getSuccessSize() {
      return (this.success == null) ? 0 : this.success.size();
    }

    public java.util.Iterator<Behind> getSuccessIterator() {
      return (this.success == null) ? null : this.success.iterator();
    }

    public void addToSuccess(Behind elem) {
      if (this.success == null) {
        this.success = new ArrayList<Behind>();
      }
      this.success.add(elem);
    }

    public List<Behind> getSuccess() {
      return this.success;
    }

    public getBehindByMediaIds_result setSuccess(List<Behind> success) {
      this.success = success;
      return this;
    }

    public void unsetSuccess() {
      this.success = null;
    }

    /** Returns true if field success is set (has been assigned a value) and false otherwise */
    public boolean isSetSuccess() {
      return this.success != null;
    }

    public void setSuccessIsSet(boolean value) {
      if (!value) {
        this.success = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case SUCCESS:
        if (value == null) {
          unsetSuccess();
        } else {
          setSuccess((List<Behind>)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case SUCCESS:
        return getSuccess();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case SUCCESS:
        return isSetSuccess();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof getBehindByMediaIds_result)
        return this.equals((getBehindByMediaIds_result)that);
      return false;
    }

    public boolean equals(getBehindByMediaIds_result that) {
      if (that == null)
        return false;

      boolean this_present_success = true && this.isSetSuccess();
      boolean that_present_success = true && that.isSetSuccess();
      if (this_present_success || that_present_success) {
        if (!(this_present_success && that_present_success))
          return false;
        if (!this.success.equals(that.success))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      return 0;
    }

    public int compareTo(getBehindByMediaIds_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;
      getBehindByMediaIds_result typedOther = (getBehindByMediaIds_result)other;

      lastComparison = Boolean.valueOf(isSetSuccess()).compareTo(typedOther.isSetSuccess());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSuccess()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, typedOther.success);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
      }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("getBehindByMediaIds_result(");
      boolean first = true;

      sb.append("success:");
      if (this.success == null) {
        sb.append("null");
      } else {
        sb.append(this.success);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class getBehindByMediaIds_resultStandardSchemeFactory implements SchemeFactory {
      public getBehindByMediaIds_resultStandardScheme getScheme() {
        return new getBehindByMediaIds_resultStandardScheme();
      }
    }

    private static class getBehindByMediaIds_resultStandardScheme extends StandardScheme<getBehindByMediaIds_result> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, getBehindByMediaIds_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 0: // SUCCESS
              if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
                {
                  org.apache.thrift.protocol.TList _list24 = iprot.readListBegin();
                  struct.success = new ArrayList<Behind>(_list24.size);
                  for (int _i25 = 0; _i25 < _list24.size; ++_i25)
                  {
                    Behind _elem26; // required
                    _elem26 = new Behind();
                    _elem26.read(iprot);
                    struct.success.add(_elem26);
                  }
                  iprot.readListEnd();
                }
                struct.setSuccessIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, getBehindByMediaIds_result struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.success != null) {
          oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.success.size()));
            for (Behind _iter27 : struct.success)
            {
              _iter27.write(oprot);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class getBehindByMediaIds_resultTupleSchemeFactory implements SchemeFactory {
      public getBehindByMediaIds_resultTupleScheme getScheme() {
        return new getBehindByMediaIds_resultTupleScheme();
      }
    }

    private static class getBehindByMediaIds_resultTupleScheme extends TupleScheme<getBehindByMediaIds_result> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, getBehindByMediaIds_result struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetSuccess()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetSuccess()) {
          {
            oprot.writeI32(struct.success.size());
            for (Behind _iter28 : struct.success)
            {
              _iter28.write(oprot);
            }
          }
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, getBehindByMediaIds_result struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          {
            org.apache.thrift.protocol.TList _list29 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
            struct.success = new ArrayList<Behind>(_list29.size);
            for (int _i30 = 0; _i30 < _list29.size; ++_i30)
            {
              Behind _elem31; // required
              _elem31 = new Behind();
              _elem31.read(iprot);
              struct.success.add(_elem31);
            }
          }
          struct.setSuccessIsSet(true);
        }
      }
    }

  }

}
